/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosockets;

import conexionServer.SocketControlMessages;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SAMUEL-PC
 */
public class NewJFrame extends javax.swing.JFrame {

    private SocketControlMessages scm;

    private ArrayList<String> usuarios;

    private String allPublicMessages;
    private String allPrivateMessages;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        scm = new SocketControlMessages();
        usuarios = new ArrayList<>();
        allPublicMessages = "<html>";
        allPrivateMessages = "<html>";

        initComponents();

        boxUsers.removeAllItems();
        boxUsers.addItem("Para todos");
        this.buttonSendMessage.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        JPanelBackground = new javax.swing.JPanel();
        jScrollPublic = new javax.swing.JScrollPane();
        labelPublicMessages = new javax.swing.JLabel();
        jScrollPrivate = new javax.swing.JScrollPane();
        lablePrivateMessages = new javax.swing.JLabel();
        jPanelActiveUsers = new javax.swing.JPanel();
        labelActiveUsers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelUsersActive = new javax.swing.JLabel();
        jPanelSentMessages = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaMessage = new javax.swing.JTextArea();
        buttonSendMessage = new javax.swing.JButton();
        boxUsers = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonSalir = new javax.swing.JButton();
        textUserRegister = new javax.swing.JTextField();
        buttonRegister = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPublicMessages.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPublic.setViewportView(labelPublicMessages);

        lablePrivateMessages.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPrivate.setViewportView(lablePrivateMessages);

        labelActiveUsers.setText("0");

        labelUsersActive.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(labelUsersActive);

        javax.swing.GroupLayout jPanelActiveUsersLayout = new javax.swing.GroupLayout(jPanelActiveUsers);
        jPanelActiveUsers.setLayout(jPanelActiveUsersLayout);
        jPanelActiveUsersLayout.setHorizontalGroup(
            jPanelActiveUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActiveUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelActiveUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(87, 87, 87))
            .addComponent(jScrollPane1)
        );
        jPanelActiveUsersLayout.setVerticalGroup(
            jPanelActiveUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActiveUsersLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelActiveUsers)
                .addContainerGap())
        );

        areaMessage.setColumns(20);
        areaMessage.setRows(5);
        jScrollPane5.setViewportView(areaMessage);

        buttonSendMessage.setText("Enviar a");
        buttonSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendMessageActionPerformed(evt);
            }
        });

        boxUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelSentMessagesLayout = new javax.swing.GroupLayout(jPanelSentMessages);
        jPanelSentMessages.setLayout(jPanelSentMessagesLayout);
        jPanelSentMessagesLayout.setHorizontalGroup(
            jPanelSentMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSentMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSentMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSentMessagesLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelSentMessagesLayout.createSequentialGroup()
                        .addComponent(buttonSendMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxUsers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSentMessagesLayout.setVerticalGroup(
            jPanelSentMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSentMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSentMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSendMessage)
                    .addComponent(boxUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel1.setText("Mensajes Privados");

        jLabel3.setText("Mensajes Publicos");

        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        buttonRegister.setText("Registrar");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelBackgroundLayout = new javax.swing.GroupLayout(JPanelBackground);
        JPanelBackground.setLayout(JPanelBackgroundLayout);
        JPanelBackgroundLayout.setHorizontalGroup(
            JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                .addGroup(JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                                .addComponent(textUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonRegister))))
                    .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSentMessages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelActiveUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        JPanelBackgroundLayout.setVerticalGroup(
            JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                .addGroup(JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelActiveUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(JPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanelSentMessages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(JPanelBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPrivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSalir)
                        .addGap(7, 7, 7))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendMessageActionPerformed
        String mensaje = areaMessage.getText();
        if (mensaje.length() > 0) {
            if (this.boxUsers.getSelectedIndex() == 0) {
                    scm.sendPublicMessage(mensaje);                    
            } else {
                String destino = this.boxUsers.getSelectedItem().toString();
                scm.sendPrivateMessage(mensaje, destino);
            }
            areaMessage.setText("");
        }

    }//GEN-LAST:event_buttonSendMessageActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        String userToRegister = textUserRegister.getText();
        if (userToRegister.length() == 0) {

        } else {
            scm.RegisterUser(userToRegister);
            String error = scm.isUserValid();
            if (error != null) {
                this.buttonSendMessage.setEnabled(true);
                this.buttonRegister.setEnabled(false);
                this.textUserRegister.setEnabled(false);
                initUpdates();
            } else {
                JOptionPane.showMessageDialog(null, error, "ERROR_USER", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        scm.exit();
        this.buttonSendMessage.setEnabled(false);
        this.buttonRegister.setEnabled(true);
        this.textUserRegister.setEnabled(true);
        this.textUserRegister.setText("");

    }//GEN-LAST:event_buttonSalirActionPerformed
    private void initUpdates() {
        Thread updateWindow;
        scm.readText();
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    if (scm.thereAreNewUsers()) {
                        usuarios = scm.getUsers();
                        labelActiveUsers.setText("Usuarios Activos:" + (usuarios.size()-1));
                        addBoxItems();
                    }
                    if (scm.isNewPublicMessage()) {
                        showMessagePublic(scm.getMessage4All());
                    }
                    if (scm.isNewPrivateMessage()) {
                        showMessagePrivate(scm.getMessageInPrivate());
                    }
                }
            }
        };
        updateWindow = new Thread(runnable);
        updateWindow.start();
    }

    private synchronized void addBoxItems() {
        this.boxUsers.removeAllItems();
        boxUsers.addItem("Para todos");
        String content = "<html>";
        for (int i = 0; i < usuarios.size(); i++) {
            String user = usuarios.get(i);
            if (!user.equals(scm.getCurrentUser())) {
                content += user + "<br>";
                this.boxUsers.addItem(user);
            } 
        }
        this.labelUsersActive.setText(content);
    }

    private synchronized void showMessagePublic(String message) {
        allPublicMessages += message + "<br>";
        this.labelPublicMessages.setText(allPublicMessages);
    }

    private synchronized void showMessagePrivate(String message) {
        allPrivateMessages += message + "<br>";
        this.lablePrivateMessages.setText(allPrivateMessages);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBackground;
    private javax.swing.JTextArea areaMessage;
    private javax.swing.JComboBox<String> boxUsers;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JButton buttonSendMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanelActiveUsers;
    private javax.swing.JPanel jPanelSentMessages;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPrivate;
    private javax.swing.JScrollPane jScrollPublic;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelActiveUsers;
    private javax.swing.JLabel labelPublicMessages;
    private javax.swing.JLabel labelUsersActive;
    private javax.swing.JLabel lablePrivateMessages;
    private javax.swing.JTextField textUserRegister;
    // End of variables declaration//GEN-END:variables
}
